name: Camera
authors: [NidoThe1st, BoatHub, JustBru00]
version: '${project.version}'
depend: [TimingSystem]
main: com.nido.camera.CameraPlugin
api-version: 1.19
commands:
  cam:
    description: "Base command for cameras"
    aliases: []
    
permissions:
  cameras.view.hidemessages:
    description: Disables camera view teleport messages for the given user.
    default: false